# Screen implementation generated from reading ui file 'c:\Users\Spaghet\Desktop\PROGVS\GIIT\Lab4Sem\oPROG2\LAB1\untitled3.ui'
#
# Created by: PyQt5 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen(object):
    def setupUi(self, Screen):
        Screen.setObjectName("Screen")
        Screen.resize(300, 330)
        self.widget = QtWidgets.QWidget(Screen)
        self.widget.setGeometry(QtCore.QRect(10, 10, 258, 317))
        self.widget.setObjectName("widget")

        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout2.setContentsMargins(110, 0, 0, 0)
        self.verticalLayout2.setObjectName("verticalLayout2")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")

        self.verticalLayout.addWidget(self.checkBox)

        self.checkbox2 = QtWidgets.QCheckBox(self.widget)
        self.checkbox2.setObjectName("checkbox2")

        self.verticalLayout.addWidget(self.checkbox2)

        self.checkbox3 = QtWidgets.QCheckBox(self.widget)
        self.checkbox3.setObjectName("checkbox3")

        self.verticalLayout.addWidget(self.checkbox3)

        self.checkbox4 = QtWidgets.QCheckBox(self.widget)
        self.checkbox4.setObjectName("checkbox4")

        self.checkbox5 = QtWidgets.QCheckBox(self.widget)
        self.checkbox5.setObjectName("checkbox5")

        self.verticalLayout.addWidget(self.checkbox4)

        self.verticalLayout2.addLayout(self.verticalLayout)

        self.Button = QtWidgets.QPushButton(self.widget)
        self.Button.setObjectName("Button")

        self.verticalLayout2.addWidget(self.Button)

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.verticalLayout2.addWidget(self.plainTextEdit)

        self.retranslateUi(Screen)
        QtCore.QMetaObject.connectSlotsByName(Screen)

        self.checkBox.setChecked(False)
        self.checkbox2.setChecked(False)
        self.checkbox3.setChecked(False)
        self.checkbox4.setChecked(False)
        self.checkbox5.setChecked(False)

        self.Button.clicked.connect(self.ButtonPressed)

    def retranslateUi(self, Screen):
        _translate = QtCore.QCoreApplication.translate
        Screen.setWindowTitle(_translate("Mcdonalds", "Mcdonalds"))
        self.checkBox.setText(_translate("Screen", "Hamburger"))
        self.checkbox2.setText(_translate("Screen", "Добрый кола"))
        self.checkbox3.setText(_translate("Screen", "Злой кола"))
        self.checkbox4.setText(_translate("Screen", "Чикен наггет"))
        self.checkbox5.setText(_translate("Screen", "Салфетки"))
        self.Button.setText(_translate("Screen", "Заказать"))

    def ButtonPressed(self):
        self.plainTextEdit.appendPlainText("Вы заказали:")
        cost = 0
        if self.checkBox.isChecked():
            self.plainTextEdit.appendPlainText("Hamburger - 140 руб")
            cost += 140
        if self.checkbox2.isChecked():
            self.plainTextEdit.appendPlainText("Добрый кола - 100 руб")
            cost += 100
        if self.checkbox3.isChecked():
            self.plainTextEdit.appendPlainText("Злой кола - 90 рублей")
            cost += 90
        if self.checkbox4.isChecked():
            self.plainTextEdit.appendPlainText("Чикен наггет - 120 рублей")
            cost += 120
        if self.checkbox5.isChecked():
            self.plainTextEdit.appendPlainText("Салфетки - 10 рублей")
            cost += 10
        self.plainTextEdit.appendPlainText("Итого: " + str(cost))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen = QtWidgets.QWidget()
    ui = Ui_Screen()
    ui.setupUi(Screen)
    Screen.show()
    sys.exit(app.exec_())
