# Screen implementation generated from reading ui file 'c:\Users\Spaghet\Desktop\PROGVS\GIIT\Lab4Sem\oPROG2\LAB1\untitled2.ui'
#
# Created by: PyQt5 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen(object):
    def setupUi(self, Screen):
        Screen.setObjectName("Screen")
        Screen.resize(350, 200)
        self.widget = QtWidgets.QWidget(Screen)
        self.widget.setGeometry(QtCore.QRect(10, 10, 300, 170))
        self.widget.setObjectName("widget")

        self.HL_6 = QtWidgets.QHBoxLayout(self.widget)
        self.HL_6.setContentsMargins(0, 0, 0, 0)
        self.HL_6.setObjectName("HL_6")

        self.VL_5 = QtWidgets.QVBoxLayout()
        self.VL_5.setObjectName("VL_5")

        self.VL = QtWidgets.QVBoxLayout()
        self.VL.setObjectName("VL")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")

        self.VL.addWidget(self.label)

        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")

        self.VL.addWidget(self.lineEdit)

        self.VL_5.addLayout(self.VL)

        self.Button = QtWidgets.QPushButton(self.widget)
        self.Button.setObjectName("Button")

        self.VL_5.addWidget(self.Button)

        self.VL_2 = QtWidgets.QVBoxLayout()
        self.VL_2.setObjectName("VL_2")

        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")

        self.VL_2.addWidget(self.label_3)

        self.lineedit2 = QtWidgets.QLineEdit(self.widget)
        self.lineedit2.setObjectName("lineedit2")

        self.VL_2.addWidget(self.lineedit2)

        self.VL_5.addLayout(self.VL_2)

        self.HL_6.addLayout(self.VL_5)

        self.VL_3 = QtWidgets.QVBoxLayout()
        self.VL_3.setObjectName("VL_3")

        self.HL = QtWidgets.QHBoxLayout()
        self.HL.setObjectName("HL")

        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")

        self.HL.addWidget(self.label_4)

        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")

        self.HL.addWidget(self.lcdNumber)

        self.VL_3.addLayout(self.HL)

        self.HL_3 = QtWidgets.QHBoxLayout()
        self.HL_3.setObjectName("HL_3")

        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")

        self.HL_3.addWidget(self.label_5)

        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")

        self.HL_3.addWidget(self.lcdNumber_2)
        self.VL_3.addLayout(self.HL_3)

        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")

        self.VL_3.addWidget(self.label_13)
        self.HL_4 = QtWidgets.QHBoxLayout()
        self.HL_4.setObjectName("HL_4")

        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")

        self.HL_4.addWidget(self.label_6)

        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")

        self.HL_4.addWidget(self.lcdNumber_3)
        self.VL_3.addLayout(self.HL_4)

        self.HL_5 = QtWidgets.QHBoxLayout()
        self.HL_5.setObjectName("HL_5")

        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")

        self.HL_5.addWidget(self.label_12)

        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")

        self.HL_5.addWidget(self.lcdNumber_4)
        self.VL_3.addLayout(self.HL_5)
        self.HL_6.addLayout(self.VL_3)

        self.retranslateUi(Screen)
        QtCore.QMetaObject.connectSlotsByName(Screen)

        self.Button.clicked.connect(lambda: self.ButtonPressed(self.lineEdit.text(), self.lineedit2.text()))

    def retranslateUi(self, Screen):
        _translate = QtCore.QCoreApplication.translate
        Screen.setWindowTitle(_translate("Screen", "Screen"))
        self.label.setText(_translate("Screen", "Первое число(целое):"))
        self.Button.setText(_translate("Screen", "->"))
        self.label_3.setText(_translate("Screen", "Второе число(целое):"))
        self.label_4.setText(_translate("Screen", "Сумма:"))
        self.label_5.setText(_translate("Screen", "Разность:"))
        self.label_6.setText(_translate("Screen", "Произведение:"))
        self.label_12.setText(_translate("Screen", "Частное:"))

    def ButtonPressed(self, number1, number2):
        print(number1, number2)
        self.lcdNumber.display(int(number1) + int(number2))
        self.lcdNumber_2.display(int(number1) - int(number2))
        self.lcdNumber_3.display(int(number1) * int(number2))
        self.lcdNumber_4.display(int(number1) // int(number2))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen = QtWidgets.QWidget()
    ui = Ui_Screen()
    ui.setupUi(Screen)
    Screen.show()
    sys.exit(app.exec_())
