# Screen implementation generated from reading ui file 'c:\Users\Spaghet\Desktop\PROGVS\GIIT\Lab4Sem\oPROG2\LAB1\untitled.ui'
#
# Created by: PyQt5 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ButtonText(object):
    def setupUi(self, Screen):
        Screen.setObjectName("Screen")
        Screen.resize(600, 60)
        self.Textline1 = QtWidgets.QLineEdit(Screen)
        self.Textline1.setGeometry(QtCore.QRect(40, 20, 181, 21))
        self.Textline1.setObjectName("Textline")

        self.Buttn = QtWidgets.QPushButton(Screen)
        self.Buttn.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.Buttn.setObjectName("Buttn")
        
        self.Buttn.clicked.connect(lambda: self.printButtonPressed(self.Textline1.text()))
        self.Textline2 = QtWidgets.QLineEdit(Screen)
        self.Textline2.setGeometry(QtCore.QRect(380, 20, 181, 21))
        self.Textline2.setObjectName("Textline2")

        self.retranslateUi(Screen)
        QtCore.QMetaObject.connectSlotsByName(Screen)

    def retranslateUi(self, Screen):
        _translate = QtCore.QCoreApplication.translate
        Screen.setWindowTitle(_translate("Arrow", "Arrow"))
        self.Buttn.setText(_translate("Button", "->"))

    def printButtonPressed(self, text):
        pointerL = "->"
        pointerR = "<-"
        if self.Buttn.text() == pointerL:
            self.Textline2.setText(text)
            self.Buttn.setText(pointerR)
        else:
            self.Textline1.setText(self.Textline2.text())
            self.Buttn.setText(pointerL)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Screen = QtWidgets.QWidget()
    ui = ButtonText()
    ui.setupUi(Screen)
    Screen.show()
    sys.exit(app.exec_())
