# Screen implementation generated from reading ui file 'c:\Users\Spaghet\Desktop\PROGVS\GIIT\Lab4Sem\oPROG2\LAB1\untitled1.ui'
#
# Created by: PyQt5 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen(object):
    def setupUi(self, Screen):
        Screen.setObjectName("Screen")
        Screen.resize(400, 90)


        self.label = QtWidgets.QLabel(Screen)
        self.label.setGeometry(QtCore.QRect(10, 10, 16, 16))
        self.label.setText("")
        self.label.setObjectName("label")

        self.widget = QtWidgets.QWidget(Screen)
        self.widget.setGeometry(QtCore.QRect(10, 10, 360, 50))
        self.widget.setObjectName("widget")

        self.HL = QtWidgets.QHBoxLayout(self.widget)
        self.HL.setContentsMargins(0, 0, 0, 0)
        self.HL.setObjectName("HL")

        self.VL2 = QtWidgets.QVBoxLayout()
        self.VL2.setObjectName("VL2")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")

        self.VL2.addWidget(self.label)

        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")

        self.VL2.addWidget(self.lineEdit)

        self.HL.addLayout(self.VL2)

        self.Button = QtWidgets.QPushButton(self.widget)
        self.Button.setObjectName("Button")

        self.HL.addWidget(self.Button)

        self.VL = QtWidgets.QVBoxLayout()
        self.VL.setObjectName("VL")

        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")

        self.VL.addWidget(self.label_2)

        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")

        self.VL.addWidget(self.lineEdit)

        self.HL.addLayout(self.VL)

        self.retranslateUi(Screen)
        QtCore.QMetaObject.connectSlotsByName(Screen)

        self.Button.clicked.connect(lambda: self.printButtonPressed(self.lineEdit.text()))

    def retranslateUi(self, Screen):
        _translate = QtCore.QCoreApplication.translate
        Screen.setWindowTitle(_translate("Math", "Math"))
        self.label.setText(_translate("Screen", "Арифметическое выражение:"))
        self.Button.setText(_translate("Screen", "->"))
        self.label_2.setText(_translate("Screen", "Ответ:"))

    def printButtonPressed(self, text):
        self.lineEdit.setText(str(eval(text)))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen = QtWidgets.QWidget()
    ui = Ui_Screen()
    ui.setupUi(Screen)
    Screen.show()
    sys.exit(app.exec_())
